---
title: "Andromeda - Start"
author: "[Assa Yeroslaviz](https://github.com/yeroslaviz)"
format: 
  html:
    toc: true
    toc-depth: 4
    toc-expand: false
    number-sections: true
    number-depth: 4
editor: visual
date: today
bibliography: references.bib
csl: nature.csl
---

Andromeda is a peptide search engine based on probabilistic scoring. On proteome data, Andromeda performs as well as Mascot, a widely used commercial search engine, as judged by sensitivity and specificity analysis based on target decoy searches.

It can handle data with arbitrarily high fragment mass accuracy, it is also able to assign and score complex patterns of post-translational modifications, such as highly phosphorylated peptides, and accommodates extremely large databases. Andromeda can function independently or integrated into MaxQuant. This combination enables analysis of large datasets on a desktop computer. Identification of co-fragmented peptides improves the number of identified peptides.

To run Andromeda, you will need .NET framework 4.5.

# Documentation outline

This documentation is organized as a wiki, so if you find anything that is wrong or hard to understand, please [let us know](contact.html). The wiki can be browsed by using the links below or by searching with the magnifying glass in the upper right corner.

-   [maxquant - Download and installation](maxquant_instructions.html)
-   [Andromeda User Interface](andromeda_user-interface.html)
-   [Andromeda Configuration:](andromeda_configurations.html)
-   [Andromeda Tutorial](andromeda_tutorial.html)
-   [Google groups](https://groups.google.com/g/maxquant-list?pli=1)
-   [maxquant Bug reporting](https://github.com/cox-labs/CoxLab_Bug_Reporting)
-   [Glossary](Glossary.html)

You can find raw file format examples to test Andromeda \[\[http://andromeda-search.org/AndromedaExample.zip\|here\]\].

For additional training, consider attending the annual \[\[https://maxquant.org/summer_school/\|MaxQuant Summer School\]\]. Also watching some \[\[http://www.youtube.com/channel/UCKYzYTm1cnmc0CFAMhxDO 8w\|MaxQuant videos\]\] provides more insight.

\\

==== Publications ==== Cox, J., Neuhauser, N., Michalski, A., Scheltema, R. A., Olsen, J. V., and Mann, M., \[\[http://pubs.acs.org/doi/abs/10.1021/pr101065j\|Andromeda: A Peptide Search Engine Integrated into the MaxQuant Environment\]\], //J. Proteome Res.//, 2011, 10, 1794--1805
