---
title: "Andromeda Configurations"
author: "[Assa Yeroslaviz](https://github.com/yeroslaviz)"
format: 
  html:
    toc: true
    toc-depth: 4
    toc-expand: false
    number-sections: true
    number-depth: 4
editor: visual
date: today
bibliography: references.bib
csl: nature.csl
---

The Andromeda search engine[@cox2011a] offers a large variety of already defined modifications, proteases and sequence databases. But sometimes for specialized studies additional configurations are necessary. Therefore it is possible to configure the search engine according to special needs. You can add, remove, duplicate or modify modifications, enzymes and protein sequence databases. Also rearranging the order in the lists is possible to e.g. easier compare things. This rearrangements have no effect on the later analyses.

On the following pages are step by step descriptions how to configure...

-   [Andromeda modifications table](andromeda_modifications_table.html)
-   [Andromeda Enzymes - the proteases table](andromeda_enzymes.html)
-   [Andromeda Protdatabases - the (protein) sequence databases table](andromeda_protdatabases.html)

For question we would love to hear from you under [Contact](contact.html)
