---
title: "Glossary"
author: "Cox Lab"
format: 
  html:
    toc: true
    toc-depth: 4
    toc-expand: true
    number-sections: true
    number-depth: 4
    code-fold: true
    strip-comments: true
editor: visual
date: today
execute:
  eval: true
  echo: false
  message: false
  error: false
bibliography: references.bib
csl: nature.csl
---

```{r}
# install.packages("devtools")
#install.packages("glossary")
library(glossary)
#glossary_path("psyteachr")

```

===== A =====

===== B =====

===== C =====

===== D =====

===== E =====

===== F =====

```{r}
glossary_reset()
# add a definition to the table
i <- glossary("FDR", def = "False Discovery Rate", path = NULL)
i <- glossary("FTICR", def = "Fourier transform ion cyclotron resonance mass spectrometry", path = NULL)

glossary_table() # show table as kable
```

===== G =====

===== H =====

===== I =====

```{r}
glossary_reset()
# add a definition to the table
i <- glossary("iBAQ", def = "Intensity Based Absolute Quantification", path = NULL)
i <- glossary("ICAT", def = "Isotope-coded affinity tag", path = NULL)
i <- glossary("iTRAQ", def = "Isobaric tag for relative and absolute quantitation", path = NULL)

glossary_table() # show table as kable
```

===== J =====

===== K =====

===== L =====

```{r}
glossary_reset()
# add a definition to the table
i <- glossary("LFQ", def = "Label-free quantification", path = NULL)

glossary_table() # show table as kable
```

===== M =====

```{r}
glossary_reset()
# add a definition to the table
i <- glossary("MALDI", def = "Matrix-assisted laser desorption/ionization", path = NULL)

glossary_table() # show table as kable
```

===== N =====

===== O =====

===== P =====

```{r}
glossary_reset()
# add a definition to the table
i <- glossary("PAGE", def = "Polyacrylamide gel electrophoresis", path = NULL)
i <- glossary("PEP", def = "Posterior Error Probability", path = NULL)

glossary_table() # show table as kable
```

===== Q =====

===== R =====

===== S =====

```{r}
glossary_reset()
# add a definition to the table
i <- glossary("SDS", def = "sodium dodecyl sulfate", path = NULL)
i <- glossary("SILAC", def = "stable isotope labeling by/with amino acids in cell culture", path = NULL)
i <- glossary("SWIFT", def = "Stored waveform inverse Fourier transform", path = NULL)

glossary_table() # show table as kable
```

===== T =====

```{r}
glossary_reset()
# add a definition to the table
i <- glossary("TMT", def = "Tandem mass tag", path = NULL)

glossary_table() # show table as kable
```

===== U =====

===== V =====

===== W =====

===== X =====

===== Y =====

===== Z =====

------------------------------------------------------------------------

We welcome suggestions for additional entries to this glossary, or corrections to existing entries. For technical reasons, we have not made this page editable by users. Please use the following [contact](contact.html) possibilities instead.

------------------------------------------------------------------------

The glossary was created using the [glossary](https://debruine.github.io/glossary/) package[@glossary]
