---
title: "MaxQuant"
author: "[Assa Yeroslaviz](https://github.com/yeroslaviz)"
format: 
  html:
    toc: true
    toc-depth: 4
    toc-expand: false
    number-sections: true
    number-depth: 4
editor: visual
date: today
bibliography: references.bib
csl: nature.csl
---

MaxQuant is a proteomics software package designed for analyzing large mass-spectrometric data sets. It is specifically aimed at high-resolution MS data. Several labeling techniques as well as label-free quantification are supported. MaxQuant is freely available and can be downloaded from this site. The download includes the search engine [Andromeda](andromeda_instructions.html), which is integrated into MaxQuant as well as the [viewer](viewer_instructions.html) application for inspection of raw data and identification and quantification results. For statistical analysis of MaxQuant output, we offer the [Perseus](perseus_instructions.html) framework.

# Documentation outline

-   [Download and installation](Download_Installation.html)
-   [First steps in MaxQuant](MQ_FirstSteps.html)
-   [Viewer](viewer_instructions.html)
-   [Andromeda](andromeda_instructions.html)
-   [Google groups](https://groups.google.com/g/maxquant-list?pli=1)
-   [maxquant Bug reporting](https://github.com/cox-labs/CoxLab_Bug_Reporting)
-   [Glossary](Glossary.html)

For additional training, consider attending the annual [MaxQuant Summer School](https://maxquant.org/summer_school/). Also watching some [MaxQuant videos](https://www.youtube.com/c/MaxQuantChannel) provides more insight.

------------------------------------------------------------------------

For question we would love to hear from you under [Contact](contact.html)

# Bibliography

For a deep-dive into the technique and progress behind MaxQuant, many papers of varying degrees of details were published over the last decades. For further reading, you can look at a small list of the more important corner stones of the MaxQuant development history. [@cox2008] (**Note that the paper has a large supplement containing in-depth descriptions of algorithms)**,[@cox2011], [@schaab2012], [@cox2014], [@tyanova2015], [@tyanova2016] (**Note that this paper explains how to run MaxQuant in detail.**), [@sinitcyn2018]
